#define NOP_OP 0
#define PLUS_OP 1
#define MINUS_OP 2
#define TIMES_OP 3
#define DIVIDE_OP 4
#define MOD_OP 5
#define EQ_OP 6
#define NE_OP 7
#define GT_OP 8
#define LT_OP 9
#define GE_OP 10
#define LE_OP 11
#define AND_OP 12
#define OR_OP 13
#define NOT_OP 14
#define SWAP_OP 15
#define DUP_OP 16
#define HALT_OP 17
#define POP_OP 18
#define RETURN_OP 19
#define RETURNV_OP 20
#define NEG_OP 21
#define PUSHCVARIND_OP 22
#define OUTS_OP 23
#define INP_OP 24
#define PUSHFP_OP 25
#define JMPUSER_OP 26
#define TRAP_OP 27
#define RTI_OP 28
#define CALLI_OP 29
#define PUSHREG_OP 30
#define POPREG_OP 31
#define BAND_OP 32
#define BOR_OP 33
#define BXOR_OP 34
#define SHIFTL_OP 35
#define SHIFTR_OP 36
#define PUSHVARIND_OP 37
#define POPCVARIND_OP 38
#define POPVARIND_OP 39
#define COMP_OP 40
#define PUSH_OP 41
#define JUMP_OP 42
#define JUMPE_OP 43
#define PUSHVAR_OP 44
#define POPVAR_OP 45
#define ADJSP_OP 46
#define CALL_OP 47
#define PUSHCVAR_OP 48
#define POPCVAR_OP 49
#define TRACE_ON_OP 50
#define TRACE_OFF_OP 51
#define CLID_OP 52
#define SEID_OP 53
#define ILLEGAL_OP 54
