#define EXIT_CALL       1
#define PRINTI_CALL     2
#define PRINTS_CALL     3
#define PRINTC_CALL     4
#define GETS_CALL       5
#define GETL_CALL       6
#define GETI_CALL       7
#define EXEC_CALL       8
#define FORK_CALL       9
#define WAIT_CALL       10
